import { AsideMenu } from "./_components/AsideMenu";
import { BottomPlayer } from "./_components/Player/BottomPlayer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-screen h-screen overflow-x-hidden bg-[rgb(27,26,29)]">
      <AsideMenu />
      <main className="w-screen h-screen ml-24 overflow-hidden mb-10">
        {children}
      </main>
      <BottomPlayer />
    </div>
  );
}
